### ISSUE TITLE
Argentina flag is broken

### ISSUE THREAD

**Issue by bruno-vaz** [herrmannplatz/figma-country-flags-plugin#81]
| Plugin: | Correct: |
|---|---|
| ![image](https://user-images.githubusercontent.com/20361248/156651996-f1137a67-c867-47f1-90da-a5cb4be36cba.png) | ![image](https://user-images.githubusercontent.com/20361248/156651966-ce427292-0c04-46e4-b1d9-b6e2cfdfed50.png) |

**Comment by herrmannplatz** [comment]
Figma doesn't render `<use>` elements properly. I tried to come up with a fix. Let me know if it worked. Double checked with a few flags.
